apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: data
  labels:
    app: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      volumes:
        - name: mssql-data
          persistentVolumeClaim:
            claimName: mssql-pvc
      containers:
        - name: mssql
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "P@ssw0rd"
          volumeMounts:
            - name: mssql-data
              mountPath: /var/opt/mssql

      
  