apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0-management-alpine
          imagePullPolicy: IfNotPresent
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "p@ssw0rd"
          ports:
            - containerPort: 5672
            - containerPort: 15672
          volumeMounts:
            - name: rabbitmq-pvc
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-pvc
          persistentVolumeClaim:
            claimName: rabbitmq-pvc
