apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: data
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672
      name: rabbitmq
    - protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
      name: rabbitmq-ui
